name: Java 8 and Ant CI Pipeline on Red Hat Runner (No Sudo)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Verify Java 8 is already installed
      - name: Verify Java 8 Installation
        run: |
          java -version

      # Step 3: Install Apache Ant (Without sudo)
      - name: Install Apache Ant
        run: |
          # Download Apache Ant (latest stable version)
          curl -L -o ant.tar.gz https://downloads.apache.org/ant/binaries/apache-ant-1.10.11-bin.tar.gz
          
          # Extract Ant into the user's local directory
          mkdir -p ~/local/ant
          tar -xzf ant.tar.gz -C ~/local/ant --strip-components=1

          # Set Ant environment variables
          echo "export ANT_HOME=$HOME/local/ant" >> $BASH_ENV
          echo "export PATH=$ANT_HOME/bin:$PATH" >> $BASH_ENV
          source $BASH_ENV

      # Step 4: Build the project using Ant
      - name: Build with Ant
        run: |
          ant clean
          ant compile
          ant jar

      # Step 5: Run tests with Ant
      - name: Run tests with Ant
        run: |
          ant test
