name: Red Hat Self-hosted CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    # This tells GitHub Actions to use a self-hosted runner
    runs-on: self-hosted

    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up environment for Red Hat
      - name: Set up Red Hat environment
        run: |
          sudo dnf update -y
          sudo dnf install -y gcc make

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          sudo dnf install -y <your-dependency>

      # Step 4: Build the project
      - name: Build project
        run: |
          make build

      # Step 5: Run tests
      - name: Run tests
        run: |
          make test
