name: Python CI on Red Hat Runner (No Sudo)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python environment (without sudo)
      - name: Set up Python environment
        run: |
          # Create a virtual environment in the project directory
          python3 -m venv ~/myenv
          
          # Activate the virtual environment
          source ~/myenv/bin/activate

          # Upgrade pip in the virtual environment
          pip install --upgrade pip

      # Step 3: Install Python dependencies in the virtual environment
      - name: Install Python dependencies
        run: |
          source ~/myenv/bin/activate
          pip install -r requirements.txt

      # Step 4: Run Python tests
      - name: Run tests
        run: |
          source ~/myenv/bin/activate
          pytest
