name: Print a Word on Red Hat Runner

on:
  push:
    branches:
      - main

jobs:
  print_message:
    runs-on: self-hosted

    steps:
      # Step 1: Checkout the code (optional if you just want to print)
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Print a word or message
      - name: Print Hello World
        run: |
          echo "Hello, World!"

      # Step 3: Print a custom message
      - name: Print Custom Message
        run: |
          echo "This is a test on my Red Hat self-hosted runner!"
